version: "2"
services:
  cli:
    image: manaphp/php73:2.0
    volumes: 
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cli/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/cli/tmp:/var/www/html/tmp
    restart: always